spring:
  application:
    name: each-admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 3548297839e
  data:
    redis:
      host: localhost
      port: 6379
      password: pt2001
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Ov23liGr58XphUchLkN7
#            client-secret: 4988d45f0adb6312ce7c6b8b50b3a2075d7d694c
server:
  servlet:
    session:
      timeout: 120s
  port: 8080